const Map<String, String> dn = {
  'app_name': 'إمساكية رمضان',
  'home':     'Bøntider',
  'news':     'Projekter',
  'fjr':      'Fajr',
  'shorooq':  'Shurooq',
  'doher':    'Duhur',
  'asr':      'Asr',
  'mogreb':   'Maghrib',
  'esha':     'Isha',
  'emsaq':    'Emsak',
  'notify':   'Advarsel inden bøn',
  'after':    'Adhan om',
  'location': 'Vælg placering',
  'pay':      'Doner',
  '1':        'Muharram',
  '2':        'Safar',
  '3':        'Rabi al-awwal',
  '4':        'Rabi al-Thani',
  '5':        'Jumada al-awwal',
  '6': 'Jumada al-Thani',
  '7': 'Rajab',
  '8': 'Sha`ban',
  '9': 'Ramadan',
  '10': 'Dhul Qa\'dah',
  '11': 'Shawwal',
  '12': 'Dhul Hijjah',
  'sun': 'Søndag',
  'mon': 'Mandag',
  'tus': 'Tirsdag',
  'wed': 'Onsdag',
  'thir': 'Torsdag',
  'fri': 'Fredag',
  'sat': 'Lørdag',
  'emsaknow': 'Emsak Nu',
  'dhrnow': 'Duhur Adhan Nu',
  'asrnow': 'Asr Adhan Nu',
  'magrebnow': 'Maghrib Adhan Nu',
  'ishanow': 'Isha Adhan Nu',
  'fjrnow': 'Fajr Adhan Nu',
  'choose': 'Vælg en by',
  'search': 'Søg',
  'about':'HVEM ER ASSALAM',
  'about_body':'Assalam Charity, er en uafhængig europæisk social og velgørenhedsorganisation som blev etableret i Danmark og har ingen politiske bånd.Vi yder vores hjælp og service til alle uanset vedkommendes politiske eller religiøse tilhørsforhold.Vi arbejder på at hjælpe der hvor nøden er størst. Det gør vi gennem  nødhjælpsarbejde og projekter der fremmer samfunds og miljøudvikling samt projekter inden for forskellige områder. Vi støtter:',
  'body1':'• sociale myndigheder',
  'body2':'• Sportsaktiviteter.',
  'body4':'• Uddannelse.',
  'body5':'• Flygtninge og folk i nød.',
  'body6':'• Nødhjælp til dem, der er ramt af katastrofer og krige.',
  'body7':'• Sikring af forældreløse og enker.',
  'body8':'• Hjælper personer med særlige behov.',
  'and_other':'Og andre projekter ...',
  'vesion':'VISION',
  'vesion_body':'''Vi vil være en af de førende indenfor nødhjælp og velgørenhed samt socialarbejde, både i Danmark og uden for Danmark.''',
  'message':'MISSION',
  'message_body':'Vi sørger for at yde økonomisk hjælp og nødhjælp til de mest fattige og trængende i verden. Vi ønsker at sikre de forældreløse og hårdest ramte familier de bedst mulig levevilkår. Vi ønsker at sætte særlig fokus på den opgaver det er at sikre nødhjælp til de mange med særlige behov herunder mennesker med handicap.',
  'qeam':'VÆRDIER',
  'qeam_body1':'• Retfærdighed',
  'qeam_body2':'• Kvalitet',
  'qeam_body4':'• Samarbejde på tværs',
  'qeam_body3':'• Gennemsigtighed',
  'qeam_body5':'• Bæredygtig udvikling',
  'ar':'العربية',
  'dn':'Danish',
  'info':'Bønnetiderne for denne kalender er godkendt af Den Islamiske union i Danmark, som Assalam Charity er et af dets medlemmer.'
  ,'country':'Land',
  'about_us':'ASSALAM',
};
